services:
  openmrs:
    environment:
      OMRS_CREATE_TABLES: ${OMRS_CREATE_TABLES:-true}
      OMRS_AUTO_UPDATE_DATABASE: ${OMRS_AUTO_UPDATE_DATABASE:-false}
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-openmrs.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && PathPrefix(`/openmrs`)"
      traefik.http.routers.bahmni-openmrs.entrypoints: "websecure"
      traefik.http.services.bahmni-openmrs.loadbalancer.server.port: 8080
    volumes:
      - "${BAHMNI_OPENMRS_MODULES_PATH:?}/:/openmrs/data/modules/"
      - "${BAHMNI_CONFIG_OVERRIDE_PATH:?}/properties:/etc/properties/"
      - "${BAHMNI_CONFIG_OVERRIDE_PATH:?}/properties/erp.properties:/openmrs/data/erp.properties"
    networks:
      ozone:
      web:

  bahmni-web:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && (PathPrefix(`/bahmni`) || PathPrefix(`/person-management`) || PathPrefix(`/cgi-bin`))"
      traefik.http.routers.bahmni.entrypoints: "websecure"
      traefik.http.services.bahmni.loadbalancer.server.port: 8091

      traefik.http.middlewares.frontend-stripprefix.stripprefix.prefixes: /bahmni/home
      traefik.http.middlewares.frontend-stripprefix.stripprefix.forceslash: false
      traefik.http.middlewares.home-redirectregex.redirectregex.regex: https://${BAHMNI_EMR_HOSTNAME}/bahmni
      traefik.http.middlewares.home-redirectregex.redirectregex.replacement: https://${BAHMNI_EMR_HOSTNAME}/bahmni/home
      traefik.http.middlewares.root-redirectregex.redirectregex.regex: https://${BAHMNI_EMR_HOSTNAME}
      traefik.http.middlewares.root-redirectregex.redirectregex.replacement: https://${BAHMNI_EMR_HOSTNAME}/bahmni/home
      traefik.http.middlewares.gzip.compress: true
    networks:
      ozone:
      web:

  implementer-interface:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-implementer-interface.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && PathPrefix(`/implementer-interface`)"
      traefik.http.routers.bahmni-implementer-interface.entrypoints: "websecure"
      traefik.http.services.bahmni-implementer-interface.loadbalancer.server.port: 80
    networks:
      ozone:
      web:

  reports:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-reports.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && PathPrefix(`/bahmnireports`)"
      traefik.http.routers.bahmni-reports.entrypoints: "websecure"
      traefik.http.services.bahmni-reports.loadbalancer.server.port: 8051
    networks:
      ozone:
      web:

  patient-documents:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-patient-documents.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && (PathPrefix(`/document_images`) || PathPrefix(`/uploaded_results`) || PathPrefix(`/uploaded-files`))"
      traefik.http.routers.bahmni-patient-documents.entrypoints: "websecure"
      traefik.http.services.bahmni-patient-documents.loadbalancer.server.port: 80
    networks:
      ozone:
      web:

  appointments:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-appointments.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && PathPrefix(`/appointments`)"
      traefik.http.routers.bahmni-appointments.entrypoints: "websecure"
      traefik.http.services.bahmni-appointments.loadbalancer.server.port: 80
    networks:
      ozone:
      web:

  ipd:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bahmni-ipd.rule: "Host(`${BAHMNI_EMR_HOSTNAME}`) && PathPrefix(`/ipd`)"
      traefik.http.routers.bahmni-ipd.entrypoints: "websecure"
      traefik.http.services.bahmni-ipd.loadbalancer.server.port: 80
    networks:
      ozone:
      web:

  eip-odoo-openmrs:
    environment:
      - EIP_DRUG_ORDER_TYPE_UUID=16bb6bcf-2e81-4ba5-8583-ff4913201a72
      - ENABLE_ENCOUNTER_LOCATION_TO_COMPANY_MAPPING=${ENABLE_ENCOUNTER_LOCATION_TO_COMPANY_MAPPING}
